# Will the durability of the scissors be wasted when creating an invisible item frame
# Default: true
damagingShears: true

# Is it possible to leave an empty invisible item frame
# Default: false
allowEmptyItemFrame: false